### ISSUE TITLE
Question about `coxpsmatch()` and exact matching

### ISSUE THREAD

**Issue by skent259** [skent259/rsmatch#10]
@pauknemj what would happen in your function when using exact matching with a limited number of pairs?  

I see that this section of code grabs the top `n_pairs`:

```r
if(length(matches$trt.id) > n_pairs) {
    matches <- matches[1:n_pairs,, drop = FALSE]
  }
```

But will the numbering grab a biased number from a given exact match group?  For example, if you had two equal-sized exact match groups and asked for half of the maximum pairs, would it give you pretty much everyone from the first group?

**Comment by pauknemj** [comment]
I don't think so. They are collectively ordered by distance first.
________________________________
From: Sean Kent ***@***.***>
Sent: Wednesday, May 19, 2021 9:16 PM
To: skent259/rsmatch ***@***.***>
Cc: MITCHELL JOSEPH PAUKNER ***@***.***>; Mention ***@***.***>
Subject: [skent259/rsmatch] Question about `coxpsmatch()` and exact matching (#10)


@pauknemj<https://github.com/pauknemj> what would happen in your function when using exact matching with a limited number of pairs?

I see that this section of code grabs the top n_pairs:

if(length(matches$trt.id) > n_pairs) {
    matches <- matches[1:n_pairs,, drop = FALSE]
  }

But will the numbering grab a biased number from a given exact match group? For example, if you had two equal-sized exact match groups and asked for half of the maximum pairs, would it give you pretty much everyone from the first group?
